# Generated by Django 6.0 on 2025-12-22 00:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_nominal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('taxa_juros', models.FloatField()),
                ('ip', models.GenericIPAddressField()),
                ('data_solicitacao', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccb.emprestimo')),
            ],
        ),
    ]
