# Generated by Django 6.0 on 2025-12-22 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_quitacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_nominal',
            field=models.DecimalField(decimal_places=2, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
