# Generated by Django 6.0 on 2025-12-23 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccb', '0003_alter_emprestimo_valor_nominal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
