# Generated by Django 6.0 on 2025-12-23 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccb', '0004_alter_emprestimo_data_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
